manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tlsjoeguy
      url-base: https://github.com/TLSJoeguy
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboard-tm
      remote: tlsjoeguy
      revision: main
  self:
    path: config
